
// Character
export const ADD_REWARD = 'GET_REWARD'
export const SET_GOLD = 'SET_GOLD'
export const SET_ROLLS = 'SET_ROLLS'
export const SET_ROLL_TIMER = 'SET_ROLL_TIMER'

// Items
export const ADD_ITEM_TO_INV = 'ADD_ITEM_TO_INV'
export const REMOVE_INV_ITEMS = 'REMOVE_INV_ITEMS'
export const UNSELECT_INV_ITEMS = 'UNSELECT_INV_ITEMS'
export const UNSELECT_SHOP_ITEMS = 'UNSELECT_SHOP_ITEMS'
export const SET_INV_ITEM_SELECT = 'SET_INV_ITEM_SELECT'
export const SET_SHOP_ITEM_SELECT = 'SET_SHOP_ITEM_SELECT'
export const REROLL_ITEMS = 'REROLL_ITEMS'
export const REMOVE_SHOP_ITEM = 'REMOVE_SHOP_ITEM'
export const EQUIP_ITEM = 'EQUIP_ITEM'
export const SET_CRAFTABLE_ITEM_SELECT = 'SET_CRAFTABLE_ITEM_SELECT'
export const UNSELECT_CRAFTABLE_ITEMS = 'UNSELECT_CRAFTABLE_ITEMS'
export const REMOVE_DROPS_FROM_INV = 'REMOVE_DROPS_FROM_INV'
export const SORT_ITEMS = 'SORT_ITEMS'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'

// Dungeon
export const ADD_DUNGEON = 'ADD_DUNGEON'

// Game
export const START_GAME = 'START_GAME'
export const END_GAME = 'END_GAME'
export const SET_CAN_ATTACK = 'CANT_ATTACK'
export const SET_BATTLE_STATUS = 'SET_BATTLE_STATUS'
export const ITEM_OBTAINED = 'ITEM_OBTAINED'
export const GENERATE_CLASSIC_ENEMIES = 'GENERATE_CLASSIC_ENEMIES'

// Player
export const RESET_PLAYER = 'RESET_PLAYER'
export const PLAYER_BLOCKED = 'PLAYER_BLOCKED'
export const PLAYER_HIT = 'PLAYER_HIT'
export const RESET_PLAYER_DMG_TAKEN = 'RESET_PLAYER_DMG_TAKEN'
export const UPDATE_PLAYER_STATS = 'UPDATE_PLAYER_STATS'

// Enemy
export const SET_ENEMY = 'SET_ENEMY'
export const CLEAR_ENEMY = 'CLEAR_ENEMY'
export const ENEMY_DODGED = 'ENEMY_DODGED'
export const ENEMY_HIT = 'ENEMY_HIT'
export const RESET_ENEMY_DMG_TAKEN = 'RESET_ENEMY_DMG_TAKEN'

// Loading
export const RESET_STATE = 'RESET_STATE'
export const LOAD_STATE = 'LOAD_STATE'
